input {
  beats {
    port => 5044
  }
}

filter {
  if [log_format] == "json" {
    json {
      source => "message"
      target => "parsed"
    }
    if "_jsonparsefailure" not in [tags] {
      ruby {
        code => 'event.get("parsed").each { |k,v| event.set(k,v) } rescue nil'
      }
      mutate { remove_field => ["parsed"] }
    }
    date {
      match => ["time", "ISO8601", "yyyy-MM-dd HH:mm:ss", "UNIX_MS"]
      target => "@timestamp"
    }
  }
  mutate {
    remove_field => ["agent", "ecs", "input", "log", "host"]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "logs-%{[app_name]}-%{+YYYY.MM.dd}"
  }
}
